version: '3.8'

services:
  lara-drops:
    image: alpine:latest
    container_name: ${APP_NAME}
    labels:
      - "promtail.scrape=true"
    restart: always

    volumes:
      - lara_drops:/app

    environment:
      - APP_NAME=${APP_NAME}
      - RELEASE_VERSION=${RELEASE_VERSION}
      
    networks:
      - default

    entrypoint: |
      /bin/sh -c "
      # 1. Install Python 3 & basic tools
      apk add --no-cache python3 py3-pip tar curl;

      # 2. Download code if it does not exist locally
      if [ ! -d /app/lara-drops-v${RELEASE_VERSION} ]; then
        mkdir -p /app/lara-drops-v${RELEASE_VERSION} && \
        curl -L https://github.com/DevinMB/lara-drops/archive/refs/tags/v${RELEASE_VERSION}.tar.gz | tar xz --strip-components=1 -C /app/lara-drops-v${RELEASE_VERSION};
      fi

      # 3. Install Python dependencies
      if [ -f /app/lara-drops-v${RELEASE_VERSION}/requirements.txt ]; then
        pip3 install -r /app/lara-drops-v${RELEASE_VERSION}/requirements.txt --break-system-packages;
      else
        echo 'No requirements.txt found, skipping installation';
      fi

      # 4. Run Python script
      python3 /app/lara-drops-v${RELEASE_VERSION}/main.py;

      # 5. Keep container running
      tail -f /dev/null
      "
networks:
  default:
    driver: bridge

volumes:
  lara_drops: